package tools;

import java.util.HashMap;
import java.util.Map;

public class CountryCode {

	private static Map<String, String> c = new HashMap<String, String>();
	
	public CountryCode() {
		
	}
	
	public static void init() {
		c.put("af","Afghanistan");
		c.put("al","Albania");
		c.put("dz","Algeria");
		c.put("ad","Andorra");
		c.put("ao","Angola");
		c.put("ag","Antigua and Barbuda");
		c.put("ar","Argentina");
		c.put("am","Armenia");
		c.put("au","Australia");
		c.put("at","Austria");
		c.put("az","Nagorno-Karabakh");
		c.put("bs","Bahamas");
		c.put("bh","Bahrain");
		c.put("bd","Bangladesh");
		c.put("bb","Barbados");
		c.put("by","Belarus");
		c.put("be","Belgium");
		c.put("bz","Belize");
		c.put("bj","Benin");
		c.put("bt","Bhutan");
		c.put("bo","Bolivia");
		c.put("ba","Bosnia and Herzegovina");
		c.put("bw","Botswana");
		c.put("br","Brazil");
		c.put("bn","Brunei");
		c.put("bg","Bulgaria");
		c.put("bf","Burkina Faso");
		c.put("bi","Burundi");
		c.put("kh","Cambodia");
		c.put("cm","Cameroon");
		c.put("ca","Canada");
		c.put("cv","Cape Verde");
		c.put("cf","Central African Republic");
		c.put("td","Chad");
		c.put("cl","Chile");
		c.put("co","Colombia");
		c.put("km","Comoros");
		c.put("cd","Repulic of Congo");
		c.put("cg","Congo");
		c.put("cr","Costa Rica");
		c.put("ci","Cote d'Ivoire (Ivory Coast)");
		c.put("hr","Croatia");
		c.put("cu","Cuba");
		c.put("cy","Northern Cyprus");
		c.put("cz","Czech Republic");
		c.put("dk","Denmark");
		c.put("dj","Djibouti");
		c.put("dm","Dominica");
		c.put("do","Dominican Republic");
		c.put("ec","Ecuador");
		c.put("eg","Egypt");
		c.put("sv","El Salvador");
		c.put("gq","Equatorial Guinea");
		c.put("er","Eritrea");
		c.put("ee","Estonia");
		c.put("et","Ethiopia");
		c.put("fj","Fiji");
		c.put("fi","Finland");
		c.put("fr","France");
		c.put("ga","Gabon");
		c.put("gm","Gambia");
		c.put("ge","South Ossetia");
		c.put("de","Germany");
		c.put("gh","Ghana");
		c.put("gr","Greece");
		c.put("gd","Grenada");
		c.put("gt","Guatemala");
		c.put("gn","Guinea");
		c.put("gw","Guinea-Bissau");
		c.put("gy","Guyana");
		c.put("ht","Haiti");
		c.put("hn","Honduras");
		c.put("hu","Hungary");
		c.put("is","Iceland");
		c.put("in","India");
		c.put("id","Indonesia");
		c.put("ir","Iran");
		c.put("iq","Iraq");
		c.put("ie","Ireland");
		c.put("il","Israel");
		c.put("it","Italy");
		c.put("jm","Jamaica");
		c.put("jp","Japan");
		c.put("jo","Jordan");
		c.put("kz","Kazakhstan");
		c.put("ke","Kenya");
		c.put("ki","Kiribati");
		c.put("kp","North Korea");
		c.put("kr","South Korea");
		c.put("kw","Kuwait");
		c.put("kg","Kyrgyzstan");
		c.put("la","Laos");
		c.put("lv","Latvia");
		c.put("lb","Lebanon");
		c.put("ls","Lesotho");
		c.put("lr","Liberia");
		c.put("ly","Libya");
		c.put("li","Liechtenstein");
		c.put("lt","Lithuania");
		c.put("lu","Luxembourg");
		c.put("mk","Macedonia");
		c.put("mg","Madagascar");
		c.put("mw","Malawi");
		c.put("my","Malaysia");
		c.put("mv","Maldives");
		c.put("ml","Mali");
		c.put("mt","Malta");
		c.put("mh","Marshall Islands");
		c.put("mr","Mauritania");
		c.put("mu","Mauritius");
		c.put("mx","Mexico");
		c.put("fm","Micronesia");
		c.put("md","Pridnestrovie (Transnistria)");
		c.put("mc","Monaco");
		c.put("mn","Mongolia");
		c.put("me","Montenegro");
		c.put("ma","Morocco");
		c.put("mz","Mozambique");
		c.put("mm","Myanmar (Burma)");
		c.put("na","Namibia");
		c.put("nr","Nauru");
		c.put("np","Nepal");
		c.put("nl","Netherlands");
		c.put("nz","New Zealand");
		c.put("ni","Nicaragua");
		c.put("ne","Niger");
		c.put("ng","Nigeria");
		c.put("no","Norway");
		c.put("om","Oman");
		c.put("pk","Pakistan");
		c.put("pw","Palau");
		c.put("pa","Panama");
		c.put("pg","Papua New Guinea");
		c.put("py","Paraguay");
		c.put("pe","Peru");
		c.put("ph","Philippines");
		c.put("pl","Poland");
		c.put("pt","Portugal");
		c.put("qa","Qatar");
		c.put("ro","Romania");
		c.put("ru","Russia");
		c.put("rw","Rwanda");
		c.put("kn","Saint Kitts and Nevis");
		c.put("lc","Saint Lucia");
		c.put("vc","Saint Vincent and the Grenadines");
		c.put("ws","Samoa");
		c.put("sm","San Marino");
		c.put("st","Sao Tome and Principe");
		c.put("sa","Saudi Arabia");
		c.put("sn","Senegal");
		c.put("rs","Serbia");
		c.put("sc","Seychelles");
		c.put("sl","Sierra Leone");
		c.put("sg","Singapore");
		c.put("sk","Slovakia");
		c.put("si","Slovenia");
		c.put("sb","Solomon Islands");
		c.put("so","Somaliland");
		c.put("za","South Africa");
		c.put("es","Spain");
		c.put("lk","Sri Lanka");
		c.put("sd","Sudan");
		c.put("sr","Suriname");
		c.put("sz","Swaziland");
		c.put("se","Sweden");
		c.put("ch","Switzerland");
		c.put("sy","Syria");
		c.put("tj","Tajikistan");
		c.put("tz","Tanzania");
		c.put("th","Thailand");
		c.put("tl","Timor-Leste (East Timor)");
		c.put("tg","Togo");
		c.put("to","Tonga");
		c.put("tt","Trinidad and Tobago");
		c.put("tn","Tunisia");
		c.put("tr","Turkey");
		c.put("tm","Turkmenistan");
		c.put("tv","Tuvalu");
		c.put("ug","Uganda");
		c.put("ua","Ukraine");
		c.put("ae","United Arab Emirates");
		c.put("gb","United Kingdom");
		c.put("us","United States");
		c.put("uy","Uruguay");
		c.put("uz","Uzbekistan");
		c.put("vu","Vanuatu");
		c.put("va","Vatican City");
		c.put("ve","Venezuela");
		c.put("vn","Vietnam");
		c.put("ye","Yemen");
		c.put("zm","Zambia");
		c.put("zw","Zimbabwe");
		c.put("cn","China");
		c.put("cx","Christmas Island");
		c.put("cc","Cocos (Keeling) Islands");
		c.put("hm","Heard Island and McDonald Islands");
		c.put("nf","Norfolk Island");
		c.put("nc","New Caledonia");
		c.put("pf","Clipperton Island");
		c.put("yt","Mayotte");
		c.put("gp","Guadeloupe");
		c.put("pm","Saint Pierre and Miquelon");
		c.put("wf","Wallis and Futuna");
		c.put("tf","French Southern and Antarctic Lands");
		c.put("bv","Bouvet Island");
		c.put("ck","Cook Islands");
		c.put("nu","Niue");
		c.put("tk","Tokelau");
		c.put("gg","Guernsey");
		c.put("im","Isle of Man");
		c.put("je","Jersey");
		c.put("ai","Anguilla");
		c.put("bm","Bermuda");
		c.put("io","British Indian Ocean Territory");
		c.put("vg","British Virgin Islands");
		c.put("ky","Cayman Islands");
		c.put("fk","Falkland Islands (Islas Malvinas)");
		c.put("gi","Gibraltar");
		c.put("ms","Montserrat");
		c.put("pn","Pitcairn Islands");
		c.put("sh","Saint Helena");
		c.put("gs","South Georgia & South Sandwich Islands");
		c.put("tc","Turks and Caicos Islands");
		c.put("mp","Northern Mariana Islands");
		c.put("pr","Puerto Rico");
		c.put("as","American Samoa");
		c.put("um","Wake Island");
		c.put("gu","Guam");
		c.put("vi","U.S. Virgin Islands");
		c.put("hk","Hong Kong");
		c.put("mo","Macau");
		c.put("fo","Faroe Islands");
		c.put("gl","Greenland");
		c.put("gf","French Guiana");
		c.put("mq","Martinique");
		c.put("re","Reunion");
		c.put("ax","Aland");
		c.put("aw","Aruba");
		c.put("an","Netherlands Antilles");
		c.put("sj","Svalbard");
		c.put("ac","Ascension");
		c.put("ta","Tristan da Cunha");
		c.put("aq","British Antarctic Territory");
	}
	
	public static String getCountry(String code) {
		
		if(c.size() == 0)
			init();
		
		String res = c.get(code);
		if(res == null)
			return code;
		
		return res;
	}
	
}
